spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.61.188:3306/td_sms?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: zhaozhebo
    password: TrialData@123
server:
  port: 8080
